#include "src/PFC_ACTUATOR/PFC_ACTUATOR.h"
#include "src/PFC_SENSOR/PFC_SENSOR.h"

#include "I2CSoilMoistureSensor.h"
#include <Wire.h>
#include "DHT.h"
#include "RunningAverage.h"

#define PH_PIN A0

#define DHTTYPE DHT11
#define DHTPIN 6
#define ARDUINO_ADDR 8


#define BYTE_SLAVE_AUTO 1
#define BYTE_SLAVE_MANUAL 2

#define BYTE_MANUAL_SET_PUMP_OFF 10
#define BYTE_MANUAL_SET_PUMP_ON 20
#define BYTE_MANUAL_SET_LIGHT_OFF 11
#define BYTE_MANUAL_SET_LIGHT_ON 21
#define BYTE_MANUAL_SET_FAN_OFF 12
#define BYTE_MANUAL_SET_FAN_ON 22
#define BYTE_MANUAL_SET_FEEDER_OFF 13
#define BYTE_MANUAL_SET_FEEDER_ON 23

#define BYTE_GET_CURR_MOISTURE 40
#define BYTE_GET_CURR_LIGHT 41
#define BYTE_GET_CURR_TEMP 42
#define BYTE_GET_CURR_PH 43
#define BYTE_GET_CURR_HUMIDITY 44

#define BYTE_GET_FILTERED_MOISTURE 50
#define BYTE_GET_FILTERED_CURR_LIGHT 51
#define BYTE_GET_FILTERED_CURR_TEMP 52
#define BYTE_GET_FILTERED_CURR_PH 53
#define BYTE_GET_FILTERED_CURR_HUMIDITY 54


